### ISSUE TITLE
Package ‘shinytools’ is not available for this version of R

### ISSUE THREAD

**Issue by EnisBerke** [ardata-fr/dgihesse#4]
Warning in install.packages :
  package ‘shinytools’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by davidgohel** [comment]
?

https://github.com/ardata-fr/shinytools#installation

**Comment by davidgohel** [comment]
this package is not maintained anymore. Don't use it :)
